// Marketing landing page shown when no one is logged in (route "/").
// Has a hero, a features section, and buttons for sign-up/login. No logic —
// purely presentational.
import { Link } from "react-router-dom";
import { Sparkles, Target, Brain, TrendingUp } from "lucide-react";

// The four feature cards displayed in the Features section.
const features = [
  { icon: Target, title: "Track Interviews", desc: "Store and organize all your interview experiences in one place." },
  { icon: Brain, title: "AI-Powered Answers", desc: "Get ideal answers generated by AI for your interview questions." },
  { icon: TrendingUp, title: "Performance Analysis", desc: "Analyze your strengths and weaknesses with detailed insights." },
  { icon: Sparkles, title: "Improve Continuously", desc: "Follow personalized study plans and improve every day." },
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-white">
      <header className="flex items-center justify-between px-8 py-5 border-b border-gray-100">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-brand-600 flex items-center justify-center">
            <Sparkles className="w-4 h-4 text-white" />
          </div>
          <span className="font-bold text-lg">InterviewVault</span>
        </div>
        <nav className="hidden md:flex items-center gap-8 text-sm font-medium text-gray-600">
          <a href="#features">Features</a>
          <a href="#how">How it Works</a>
        </nav>
        <Link to="/register" className="bg-brand-600 text-white text-sm font-medium px-4 py-2 rounded-lg hover:bg-brand-700 transition">
          Get Started
        </Link>
      </header>

      <section className="px-8 py-20 max-w-3xl mx-auto text-center">
        <span className="inline-flex items-center gap-1.5 bg-brand-50 text-brand-700 text-xs font-medium px-3 py-1.5 rounded-full mb-6">
          <Sparkles className="w-3.5 h-3.5" /> AI-Powered Interview Preparation
        </span>
        <h1 className="text-5xl font-extrabold tracking-tight text-gray-900 leading-tight">
          Prepare Better.
          <br />
          Perform <span className="text-brand-600">Smarter.</span>
        </h1>
        <p className="mt-5 text-gray-500 text-lg">
          Store your real interview experiences, get AI-powered feedback on your own answers, and
          track your progress toward every offer.
        </p>
        <div className="mt-8 flex items-center justify-center gap-3">
          <Link to="/login" className="bg-brand-600 text-white font-medium px-6 py-3 rounded-lg hover:bg-brand-700 transition">
            Sign In
          </Link>
        </div>
      </section>

      <section id="features" className="px-8 py-16 bg-gray-50">
        <h2 className="text-2xl font-bold text-center text-gray-900 mb-10">
          Everything you need to crack interviews
        </h2>
        <div className="max-w-5xl mx-auto grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
          {features.map(({ icon: Icon, title, desc }) => (
            <div key={title} className="bg-white rounded-2xl border border-gray-100 p-6 shadow-card">
              <div className="w-10 h-10 rounded-xl bg-brand-50 flex items-center justify-center mb-4">
                <Icon className="w-5 h-5 text-brand-600" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-1.5">{title}</h3>
              <p className="text-sm text-gray-500">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <section id="how" className="px-8 py-16">
        <h2 className="text-2xl font-bold text-center text-gray-900 mb-10">How it Works</h2>
        <div className="max-w-4xl mx-auto grid grid-cols-1 sm:grid-cols-3 gap-5">
          {[
            { step: "01", title: "Log your interviews", desc: "Add every interview you attend along with the questions you faced." },
            { step: "02", title: "Review with AI", desc: "Get ideal answers and feedback for each question to learn what to improve." },
            { step: "03", desc: "Track your progress across interviews and walk into your next one prepared.", title: "Improve every time" },
          ].map(({ step, title, desc }) => (
            <div key={step} className="rounded-2xl border border-gray-100 p-6 shadow-card">
              <span className="text-3xl font-extrabold text-brand-600">{step}</span>
              <h3 className="font-semibold text-gray-900 mt-3 mb-1.5">{title}</h3>
              <p className="text-sm text-gray-500">{desc}</p>
            </div>
          ))}
        </div>
      </section>

      <footer className="px-8 py-8 text-center text-sm text-gray-400 border-t border-gray-100">
        © {new Date().getFullYear()} InterviewVault. Built for tracking real interview growth.
      </footer>
    </div>
  );
}
